[tools]
bun = "latest"
cloudflared = "latest"
codex = "latest"
deno = "latest"
"gem:zsteg" = "latest"
gemini = "latest"
htmlq = "latest"
lazydocker = "latest"
lazygit = "latest"
"npm:@playwright/cli" = "latest"
"npm:@playwright/mcp" = "latest"
"npm:playwright" = "latest"
opencode = "latest"
"pipx:pgcli" = "latest"
"pipx:smassh" = "latest"
prettier = "latest"
starship = "latest"
watchexec = "latest"
yazi = "latest"
