[tools]
actionlint = "latest"
air = "latest"
antigravity-cli = "latest"
"aqua:showwin/speedtest-go" = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
biome = "latest"
bun = "latest"
cloudflared = "latest"
codex = "latest"
deno = "latest"
gcloud = "latest"
"gem:zsteg" = "latest"
gemini-cli = { version = "latest", allow_builds = ["@github/keytar", "node-pty"] }
htmlq = "latest"
lazydocker = "latest"
lazygit = "latest"
prettier = "latest"
starship = "latest"
watchexec = "latest"
