unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g allow-passthrough on # to support kitty protocol
set -g display-time 4000 # Display all messages for 4 seconds instead of 750ms
set -g base-index 1 # Start windows index at 1 instead of 0.
set -g pane-base-index 1
set -g mode-keys vi
set -g status-keys emacs
set -g set-clipboard on # Enable OSC52 clipboard integration
set -g focus-events on # For nvim
set -s escape-time 5 # Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -g history-limit 100000
set -g mouse on
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",$TERM:Tc" # True color settings

# Keybinds
bind v copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel
# bind v copy-mode
bind R source-file ${XDG_CONFIG_HOME}/tmux/tmux.conf \; display "Reloaded tmux.conf"
bind C-s attach-session -c "#{pane_current_path}" \; display "Changed session directory to #{pane_current_path}"
bind f run-shell '~/.dotfiles/bin/tmux-sessionizer.sh'
# bind -n M-f run-shell "~/.dotfiles/bin/tmux-layoutizer.sh"
bind u run-shell '~/.dotfiles/bin/tmux-url-extractor.sh'
bind W confirm-before -p "Kill session #S? (y/n)" kill-session

bind-key -n C-PPage previous-window
bind-key -n C-NPage next-window
bind-key -n C-S-PPage swap-window -t -1\; select-window -t -1
bind-key -n C-S-NPage swap-window -t +1\; select-window -t +1

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# Keybinds: open projects
bind h run-shell '~/.dotfiles/bin/tmux-sessionizer.sh ~'
bind C-d run-shell '~/.dotfiles/bin/tmux-sessionizer.sh ~/dev'
bind e run-shell 'tmuxinator start dotfiles'
bind a run-shell 'tmuxinator start dotfiles'
# bind v  run-shell '~/.dotfiles/bin/tmux-sessionizer.sh "$HOME/Documents/TU-Berlin/Master-semester-1/CSB - Cloud Service Benchmarking/valkey-benchmark/"'
bind g  run-shell '~/.dotfiles/bin/tmux-sessionizer.sh ~/dev/wikigraph'
bind y  run-shell '~/.dotfiles/bin/tmux-sessionizer.sh ~/dev/maxmed'
bind k  run-shell 'tmuxinator start maxmed'
bind j  run-shell '~/.dotfiles/bin/tmux-sessionizer.sh ~/dev/map-project'

# Style
set -g status-style bg=black
set -g status-left "#[bg=default,fg=default,bold]#{?client_prefix,,#S}#[bg=blue,fg=black,bold]#{?client_prefix,#S,}#[bg=default,fg=default,bold] | "
set -g status-left-length 25
set -g window-status-current-style "fg=white,bg=blue"
set -g window-status-style "fg=white"
set -g status-right " #h"
set -g status-right-length 25
