[ids]
*
-4653:0004
-16c0:27db
# applies to all keyboards; replace with VID:PID if you only want one device

[main]
leftcontrol=layer(alt)
leftalt=layer(control)

rightmeta=layer(control)

tab = overload(tab_hold, tab)
capslock = overload(nav, esc)

leftshift+leftmeta+f23 = rightmeta

# [hyper:C-M-A-S]
[meh:C-M-A]

[tab_hold:M]

[nav]
a = home
s = print
e = end
d = pagedown
u = pageup
h = left
j = down
k = up
l = right
n = C-pagedown
p = C-pageup
o = A-left
i = A-right
1 = M-A-1
2 = M-A-2
3 = M-A-3
4 = M-A-4
5 = M-A-5
6 = M-A-6
7 = M-A-7
8 = M-A-8
9 = M-A-9
0 = M-A-10
- = A-up
backspace = delete
/=playpause
m = mute
down = volumedown
up = volumeup
left = previoussong
right = nextsong
space = oneshot(meh)
